### ISSUE TITLE
Installation assistance

### ISSUE THREAD

**Issue by FearlessNA** [Xantios/cockpit-docker#2]
The [3 lines of command](https://github.com/Xantios/cockpit-docker#mods) is making and linking a DIR.
Then what, I clone this repo in my home folder and do the ./run -f ?
And do I already need cockpit installed, or will this launch cockpit inside a docker?

I am looking to add the container tab to my VPS with Cockpit installed on.

**Comment by Xantios** [comment]
Hey,

First of all, thanks for your interest in this plugin.

Yes, you should install cockpit first because this is a plugin. it does not come with its own cockpit install.
the docker file is intended to build the plugin from source. so clone this repo and run the build script as documented. the output of running the container is that you get a `dist` folder.

When you link it (or move/copy if you like) to `~/.local/share/cockpit/docker` then Cockpit picks it up as a plugin.

If you get it running feel free to make a PR to make the installation more obvious for new users. I can imagine your not the only one running into this.

**Comment by uberduck** [comment]
The current installation procedure seems to be: 

```git clone https://github.com/Xantios/cockpit-docker.git
cd cockpit-docker/
./run -f```

and then if you want to move it into your user's cockpit module, link it to `~/.local/share/cockpit/docker`, otherwise link / cp it to `/usr/share/cockpit`.

**Comment by Xantios** [comment]
Hey @uberduck ,

That would work as intended indeed.

I think im going to rewrite the readme a bit to make that more clear.

**Comment by Xantios** [comment]
Rewrote the readme, think this should clear things up a bit :-) 
if you have any questions please feel free to create a new issue
